### PR TITLE
Add missing dependency

### PR DESCRIPTION
**Pull request by crookedneighbor**
This PR does two things.

* Installs a missing flow-bin dependency that was preventing setup
* Simplifies the test command in the readme

When running `npm run flow`, I'm getting this failure:

```
.flowconfig:17 Unsupported option specified! (unsafe.enable_getters_and_setters)
```

### CODE REVIEW

**Comment by crookedneighbor** [comment]
You can see the same error in the Travis build.

**Comment by crookedneighbor** [comment]
Removing that line in the flow config gets us:

```
Monitor logs will go to /tmp/flow/zShomezSadminzSbtzSpaypal-braintree-web-client.monitor_log
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ test/tests/config.js:3:1

Cannot resolve name describe.

     1│ /* @flow */
     2│
     3│ describe(`happy cases`, () => {
     4│     it('should successfully create a client instance', () => {
     5│         // pass
     6│     });


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ test/tests/config.js:4:5

Cannot resolve name it.

     1│ /* @flow */
     2│
     3│ describe(`happy cases`, () => {
     4│     it('should successfully create a client instance', () => {
     5│         // pass
     6│     });
     7│ });


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ webpack.config.js:65:49

Cannot call qs.encode because property encode is missing in module querystring [1].

     webpack.config.js
       62│             rules: [
       63│                 {
       64│                     test:    /\.js$/,
       65│                     loader: `ifdef-loader?${ qs.encode(PREPROCESSOR_OPTS) }`
       66│                 },
       67│                 {
       68│                     test:   /sinon\.js$/,

     /tmp/flow/flowlib_cd6c249/node.js
 [1] 1361│ declare module "querystring" {
     1362│   declare function stringify(
     1363│     obj: Object,
     1364│     separator?: string,
     1365│     equal?: string,
     1366│     options?: {
     1367│       encodeURIComponent?: (str: string) => string;
     1368│     }
     1369│   ): string;
     1370│   declare function parse(
     1371│     str: string,
     1372│     separator: ?string,
     1373│     equal: ?string,
```

**Comment by crookedneighbor** [comment]
I don't see an `encode` method in querystring. https://nodejs.org/api/querystring.html

**Comment by bluepnume** [comment]
I guess it's an alias:

```javascript
> require('querystring').encode
[Function: stringify]
```

Anyway closing this -- sorry, already pushed up a change to do `npm flow-typed` in the travisrc, didn't see your pr in time.

**Pull request closed without merging**
